    - name: install nginx
      ansible.builtin.dnf:
        name: nginx 
        state: latest
    - name: reverse proxy configuration
      ansible.builtin.template:
       src: expense.conf.j2
       dest: /etc/nginx/default.d/expense.conf
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

# Making use of common role
    - name: common role
      ansible.builtin.import_role:
        name: common
        tasks_from: repeated-code

    # - name: Removing the default content
    #   ansible.builtin.file:
    #     path: /usr/share/nginx/html
    #     state: absent
    
    # - name: create a directory
    #   ansible.builtin.file:
    #     path: /usr/share/nginx/html
    #     state: directory

    # - name: download the code
    #   ansible.builtin.get_url:
    #     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    #     dest: /tmp/frontend.zip

    # - name: unzip the code
    #   ansible.builtin.unarchive:
    #     src: /tmp/frontend.zip
    #     dest: /usr/share/nginx/html

    # - name: reverse proxy configuration
    #   ansible.builtin.template:
    #     src: expense.conf.j2
    #     dest: /etc/nginx/default.d/expense.conf
      
    - name : restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
      

    
